kernel:
  image: linuxkit/kernel:4.14.34-d29d919c660334aae3ef68a03f56e125e5e0c115-dirty-amd64
  cmdline: "console=tty0 console=ttyS0,115200 console=ttyS1"
init:
  - linuxkit/init:v0.3
  - linuxkit/firmware-all:v0.3
  - linuxkit/runc:v0.3
  - linuxkit/containerd:v0.3
  - linuxkit/ca-certificates:v0.3
  - linuxkit/getty:v0.3
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.3
  - name: sysfs
    image: linuxkit/sysfs:v0.3
  - name: format
    image: linuxkit/format:v0.3
  - name: mount
    image: linuxkit/mount:v0.3
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  # - name: getty
  #   image: linuxkit/getty:v0.3
  #   env:
  #     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.3
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.3
  - name: sshd
    image: linuxkit/sshd:v0.3
  - name: ntpd
    image: linuxkit/openntpd:v0.3
  - name: wpa_supplicant
    image: hairyhenderson/ip:7e0d1333cd2912998b3c3f109c5883ed9198c359-dirty
    capabilities:
      - all
    net: host
    binds:
      - /etc/wpa_supplicant:/etc/wpa_supplicant
    command: ["/sbin/wpa_supplicant", "-i", "wlan0", "-c", "/etc/wpa_supplicant/wpa_supplicant.conf"]
  - name: docker
    image: docker:18.04.0-ce-dind
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
      - /etc/resolv.conf:/etc/resolv.conf
      - /var/lib/docker:/var/lib/docker
      - /lib/modules:/lib/modules
      - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
  - path: etc/wpa_supplicant/wpa_supplicant.conf
    source: wpa_supplicant.conf
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa_krypton.pub
    mode: "0600"
    optional: true
  - path: root/.profile
    contents: |
      alias docker="ctr -n services.linuxkit t exec -t --exec-id docker-cli-$(uuidgen) docker docker"
trust:
  org:
    # - linuxkit
    - library
